#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Skip the pre-push hook if running as part of the release process
if [ "$SKIP_HOOKS" = "true" ]; then
  echo "Skipping pre-push hook during release process."
  exit 0
fi

# Run tests
yarn test || exit 1

# Pull the latest changes from the remote branch
git pull origin main --rebase || exit 1

# Push changes with --force-with-lease to handle race conditions
git push --follow-tags --force-with-lease || exit 1